services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-server
    env_file:
      - .env
    ports:
      - "${MSSQL_PORT}:1433"
    user: root
    volumes:
      - /docker/mssql/data:/var/opt/mssql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mssql
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "mssql-server" # Connects to the SQL Server container
